### ISSUE TITLE
Has the API been changed?

### ISSUE THREAD

**Issue by mpember** [eidorb/ubank-api#2]
Until a couple of days ago, this was working fine.

Now, I am getting a 403 error when requesting http://www.ubank.com.au/v1/ubank/oauth/token.

Does this have anything to do with the mobile-compatible website being shut down?

**Comment by eidorb** [comment]
It appears to be working. You may be getting blocked temporarily by authenticating too frequently.

**Comment by mpember** [comment]
I only grab the data once a day.

I got it working again by replacing the initial URL to use the non-mobile internet banking URL and changed the client_id and scopes to match what I was seeing in my browser.

It may have just been dumb luck and a coincidence.  Either way, it seems to be working again.
